INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (1, 1000, 'Kasse', 100, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (2, 1020, 'Bankguthaben', 100, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (3, 1040, 'Postkonto', 100, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (4, 1060, 'Wertschriften', 106, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (5, 1069, 'Wertberichtigungen Wertschriften', 106, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (6, 1100, 'Forderungen aus Lieferungen und Leistungen (Debitoren)', 110, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (7, 1109, 'Delkredere', 110, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (8, 1140, 'Vorschüsse und Darlehen', 114, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (9, 1149, 'Wertberichtigungen Vorschüsse und Darlehen', 114, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (10, 1170, 'Vorsteuer MWST Material, Waren, Dienstleistungen, Energie', 114, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (11, 1171, 'Vorsteuer MWST Investitionen, übriger Betriebsaufwand', 114, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (12, 1176, 'Verrechnungssteuer', 114, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (13, 1180, 'Forderungen gegenüber Sozialversicherungen und Vorsorgeeinrichtungen', 114, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (14, 1189, 'Quellensteuer', 114, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (15, 1190, 'Sonstige kurzfristige Forderungen', 114, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (16, 1199, 'Wertberichtigungen sonstige kurzfristige Forderungen', 114, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (17, 1200, 'Handelswaren', 120, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (18, 1210, 'Rohstoffe', 120, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (19, 1220, 'Werkstoffe', 120, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (20, 1230, 'Hilfs- und Verbrauchsmaterial', 120, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (21, 1250, 'Handelswaren in Konsignation', 120, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (22, 1260, 'Fertige Erzeugnisse', 120, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (23, 1270, 'Unfertige Erzeugnisse', 120, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (24, 1280, 'Nicht fakturierte Dienstleistungen', 120, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (25, 1300, 'Bezahlter Aufwand des Folgejahres', 130, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (26, 1301, 'Noch nicht erhaltener Ertrag', 130, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (29, 1400, 'Wertschriften', 140, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (30, 1409, 'Wertberichtigungen Wertschriften', 140, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (31, 1440, 'Darlehen', 140, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (32, 1441, 'Hypotheken', 140, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (33, 1449, 'Wertberichtigungen langfristige Forderungen', 140, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (34, 1480, 'Beteiligungen', 148, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (35, 1489, 'Wertberichtigungen Beteiligungen', 148, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (36, 1500, 'Maschinen und Apparate', 150, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (37, 1509, 'Wertberichtigungen Maschinen und Apparate', 150, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (38, 1510, 'Mobiliar und Einrichtungen', 150, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (39, 1519, 'Wertberichtigungen Mobiliar und Einrichtungen', 150, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (40, 1520, 'Büromaschinen, Informatik, Kommunikationstechnologie', 150, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (41, 1529, 'Wertberichtigungen Büromaschinen, Informatik, Kommunikationstechnologie', 150, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (42, 1530, 'Fahrzeuge', 150, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (43, 1539, 'Wertberichtigungen Fahrzeuge', 150, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (44, 1540, 'Werkzeuge und Geräte', 150, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (45, 1549, 'Wertberichtigungen Werkzeuge und Geräte', 150, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (46, 1600, 'Geschäftsliegenschaften', 160, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (47, 1609, 'Wertberichtigungen Geschäftsliegenschaften', 160, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (48, 1700, 'Patente, Know-how, Lizenzen, Rechte, Entwicklungen', 170, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (49, 1709, 'Wertberichtigungen Patente, Know-how, Lizenzen, Rechte, Entwicklungen', 170, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (50, 1770, 'Goodwill', 170, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (51, 1779, 'Wertberichtigungen Goodwill', 170, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (52, 1850, 'Nicht einbezahltes Aktien-, Stamm-, Anteilschein- oder Stiftungskapital', 180, 'assetAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (74, 2000, 'Verbindlichkeiten aus Lieferungen und Leistungen (Kreditoren)', 200, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (75, 2030, 'Erhaltene Anzahlungen', 200, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (76, 2100, 'Bankverbindlichkeiten', 210, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (77, 2120, 'Verbindlichkeiten aus Finanzierungsleasing', 210, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (78, 2140, 'Übrige verzinsliche Verbindlichkeiten', 210, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (79, 2200, 'Geschuldete MWST (Umsatzsteuer)', 220, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (80, 2201, 'Abrechnungskonto MWST', 220, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (81, 2206, 'Verrechnungssteuer', 220, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (82, 2208, 'Direkte Steuern', 220, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (83, 2210, 'Sonstige kurzfristige Verbindlichkeiten', 220, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (84, 2261, 'Beschlossene Ausschüttungen', 220, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (85, 2270, 'Sozialversicherungen und Vorsorgeeinrichtungen', 220, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (86, 2279, 'Quellensteuer', 220, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (87, 2300, 'Noch nicht bezahlter Aufwand', 230, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (88, 2301, 'Erhaltener Ertrag des Folgejahres', 230, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (89, 2330, 'Kurzfristige Rückstellungen', 230, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (90, 2400, 'Bankverbindlichkeiten', 240, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (91, 2420, 'Verbindlichkeiten aus Finanzierungsleasing', 240, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (92, 2430, 'Obligationenanleihen', 240, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (93, 2450, 'Darlehen', 240, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (94, 2451, 'Hypotheken', 240, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (95, 2500, 'Übrige langfristige Verbindlichkeiten (unverzinslich)', 250, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (96, 2600, 'Rückstellungen', 260, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (97, 2800, 'Eigenkapital zu Beginn des Geschäftsjahres', 280, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (98, 2820, 'Kapitaleinlagen und Kapitalrückzüge', 280, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (99, 2850, 'Privat', 280, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (101, 2891, 'Jahresgewinn oder Jahresverlust', 280, 'liabilityAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (105, 3000, 'Produktionserlöse', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (106, 3200, 'Handelserlöse', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (107, 3400, 'Dienstleistungserlöse', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (108, 3600, 'Übrige Erlöse aus Lieferungen und Leistungen', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (109, 3700, 'Eigenleistungen', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (110, 3710, 'Eigenverbrauch', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (111, 3800, 'Erlösminderungen', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (112, 3805, 'Verluste Forderungen (Debitoren)', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (113, 3900, 'Bestandesänderungen unfertige Erzeugnisse', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (114, 3901, 'Bestandesänderungen fertige Erzeugnisse', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (115, 3940, 'Bestandesänderungen nicht fakturierte Dienstleistungen', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (116, 4000, 'Materialaufwand Produktion', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (117, 4200, 'Handelswarenaufwand', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (118, 4400, 'Aufwand für bezogene Dienstleistungen', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (119, 4500, 'Energieaufwand zur Leistungserstellung', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (120, 4900, 'Aufwandminderungen', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (121, 5000, 'Lohnaufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (122, 5700, 'Sozialversicherungsaufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (123, 5800, 'Übriger Personalaufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (124, 5900, 'Leistungen Dritter', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (125, 6000, 'Raumaufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (126, 6100, 'Unterhalt, Reparaturen, Ersatz mobile Sachanlagen', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (127, 6105, 'Leasingaufwand mobile Sachanlagen', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (128, 6200, 'Fahrzeug- und Transportaufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (129, 6260, 'Fahrzeugleasing und -mieten', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (130, 6300, 'Sachversicherungen, Abgaben, Gebühren, Bewilligungen', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (131, 6400, 'Energie- und Entsorgungsaufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (132, 6500, 'Verwaltungsaufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (133, 6570, 'Informatikaufwand inkl. Leasing', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (134, 6600, 'Werbeaufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (135, 6700, 'Sonstiger betrieblicher Aufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (136, 6800, 'Abschreibungen und Wertberichtigungen auf Positionen des
Anlagevermögens', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (137, 6900, 'Finanzaufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (138, 6950, 'Finanzertrag', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (149, 7000, 'Ertrag Nebenbetrieb', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (150, 7010, 'Aufwand Nebenbetrieb', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (151, 7500, 'Ertrag betriebliche Liegenschaft', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (152, 7510, 'Aufwand betriebliche Liegenschaft', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (153, 8000, 'Betriebsfremder Aufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (154, 8100, 'Betriebsfremder Ertrag', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (155, 8500, 'Ausserordentlicher, einmaliger oder periodenfremder Aufwand', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (156, 8510, 'Ausserordentlicher, einmaliger oder periodenfremder Ertrag', 0, 'incomeAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (157, 8900, 'Direkte Steuern', 0, 'expenseAccount');
INSERT INTO ledger.account (accountId, accountNumber, accountName, section, type) VALUES (158, 9200, 'Jahresgewinn oder Jahresverlust', 0, 'expenseAccount');